[package]
name = "wasm-crate-with-c"
version = "0.1.0"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
edition = "2018"

[lib]
name = "wasm_lib_with_c"
path = "src/lib.rs"
crate-type = ["staticlib"]

[build-dependencies]
cc = "1.0"
